version: '3.7'

services:
  app:
    image: keymetrics/pm2:latest-alpine
    extra_hosts:
      - www.example.com:10.255.4.1
    volumes:
    - .:/app
    ports:
    - 8080:8080
    working_dir: /app
    command:
    - pm2-runtime
    - start
    - pm2.yaml
